export interface Product {
  id: string
  name: string
  price: number
  originalPrice?: number
  image: string
  images: string[]
  rating?: number
  reviews?: number
  discount?: number
  isNew?: boolean
  isFeatured?: boolean
  category: string
  description: string
  specs?: {
    [key: string]: string
  }
  colors?: string[]
  sizes?: string[]
  inStock?: boolean
}

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Premium Graphic T-Shirt',
    price: 45,
    originalPrice: 65,
    image: '/product1.webp',
    images: ['/product1.webp', '/lifestyle-tee.webp'],
    rating: 4.8,
    reviews: 24,
    category: 'Clothing',
    discount: 30,
    isFeatured: true,
    description: 'Crafted from 100% organic cotton, this premium graphic t-shirt features a minimalist design and a comfortable fit. Perfect for everyday wear.',
    colors: ['Black', 'White', 'Heather Gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true
  },
  {
    id: '2',
    name: 'Premium Pullover Hoodie',
    price: 85,
    originalPrice: 120,
    image: '/product2.webp',
    images: ['/product2.webp', '/lifestyle-hoodie.webp'],
    rating: 4.9,
    reviews: 42,
    category: 'Clothing',
    discount: 29,
    isFeatured: true,
    description: 'Our signature heavy-weight hoodie is designed for ultimate comfort and durability. Featuring a soft brushed interior and a classic fit.',
    colors: ['Heather Gray', 'Black', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true
  },
  {
    id: '3',
    name: 'Canvas Tote Bag',
    price: 35,
    image: '/product3.webp',
    images: ['/product3.webp', '/chevrolet-tote.webp'],
    rating: 4.7,
    reviews: 18,
    category: 'Accessories',
    isFeatured: true,
    description: 'A durable and stylish canvas tote bag, perfect for your daily essentials. Features reinforced handles and a clean, minimalist design.',
    colors: ['Natural', 'Black'],
    inStock: true
  },
  {
    id: '4',
    name: 'Vintage Baseball Cap',
    price: 28,
    originalPrice: 35,
    image: '/product4.webp',
    images: ['/product4.webp', '/lifestyle-cap.webp'],
    rating: 4.6,
    reviews: 15,
    category: 'Accessories',
    discount: 20,
    isFeatured: true,
    description: 'Classic distressed baseball cap with adjustable strap. Made from premium cotton twill for a comfortable, lived-in feel.',
    colors: ['Charcoal', 'Navy', 'Olive'],
    inStock: true
  },
  {
    id: '5',
    name: 'Minimalist White Sneakers',
    price: 120,
    originalPrice: 150,
    image: '/product5.webp',
    images: ['/product5.webp', '/grey-goose-sneakers.webp'],
    rating: 4.9,
    reviews: 56,
    category: 'Clothing',
    discount: 20,
    isNew: true,
    description: 'Clean, minimalist sneakers handcrafted from premium leather. Features a durable rubber sole and a cushioned footbed for all-day comfort.',
    colors: ['White', 'Off-White'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    inStock: true
  },
  {
    id: '6',
    name: 'Matte Black Phone Case',
    price: 25,
    image: '/product6.webp',
    images: ['/product6.webp', '/product6.webp'],
    rating: 4.5,
    reviews: 32,
    category: 'Accessories',
    isNew: true,
    description: 'Sleek matte black phone case with a soft-touch finish. Provides excellent protection without adding bulk to your device.',
    colors: ['Matte Black', 'Navy', 'Dark Green'],
    inStock: true
  },
  {
    id: '7',
    name: 'Olive Bomber Jacket',
    price: 145,
    originalPrice: 195,
    image: '/product7.webp',
    images: ['/product7.webp', '/grey-goose-jacket.webp'],
    rating: 4.8,
    reviews: 21,
    category: 'Clothing',
    discount: 25,
    isFeatured: true,
    description: 'A modern take on the classic bomber jacket. Features a water-resistant shell, premium zippers, and a tailored fit.',
    colors: ['Olive', 'Navy', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true
  },
  {
    id: '8',
    name: 'Ribbed Crew Socks',
    price: 15,
    image: '/product8.webp',
    images: ['/product8.webp', '/product8.webp'],
    rating: 4.7,
    reviews: 12,
    category: 'Clothing',
    isNew: true,
    description: 'Premium ribbed crew socks made from a soft cotton blend. Features reinforced heel and toe for long-lasting wear.',
    colors: ['White', 'Gray', 'Black'],
    sizes: ['One Size'],
    inStock: true
  },
  {
    id: '9',
    name: 'Budweiser Classic Tee',
    price: 40,
    originalPrice: 50,
    image: '/budweiser-tee.webp',
    images: ['/budweiser-tee.webp', '/product9.webp'],
    rating: 4.6,
    reviews: 28,
    category: 'Clothing',
    discount: 20,
    description: 'Vintage-inspired Budweiser graphic t-shirt. Soft-washed for a comfortable, vintage feel.',
    colors: ['Red', 'White'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true
  },
  {
    id: '10',
    name: 'Coca-Cola Throw Blanket',
    price: 65,
    image: '/coca-cola-blanket.webp',
    images: ['/coca-cola-blanket.webp', '/product10.webp'],
    rating: 4.9,
    reviews: 15,
    category: 'Home Decor',
    isNew: true,
    description: 'Soft and cozy throw blanket featuring classic Coca-Cola patterns. Perfect for adding a touch of vintage charm to your home.',
    colors: ['Red/White'],
    inStock: true
  },
  {
    id: '11',
    name: 'Guinness Harp Mug',
    price: 18,
    image: '/guinness-mug.webp',
    images: ['/guinness-mug.webp', '/product11.webp'],
    rating: 4.8,
    reviews: 24,
    category: 'Home Decor',
    description: 'Matte black ceramic mug featuring the iconic Guinness gold harp logo. A must-have for any fan.',
    colors: ['Matte Black'],
    inStock: true
  },
  {
    id: '12',
    name: 'Chevrolet Distressed Cap',
    price: 30,
    originalPrice: 40,
    image: '/chevrolet-cap.webp',
    images: ['/chevrolet-cap.webp', '/product12.webp'],
    rating: 4.7,
    reviews: 19,
    category: 'Accessories',
    discount: 25,
    description: 'Classic Chevrolet bowtie logo embroidered on a distressed black cap. Adjustable fit.',
    colors: ['Black'],
    inStock: true
  },
  {
    id: '13',
    name: 'Silk Blend Scarf',
    price: 55,
    image: '/product-13-silk-scarf.webp',
    images: ['/product-13-silk-scarf.webp', '/lifestyle-tote.webp'],
    rating: 4.9,
    reviews: 12,
    category: 'Accessories',
    isNew: true,
    description: 'Luxurious silk blend scarf with a subtle sheen and hand-rolled edges.',
    colors: ['Champagne', 'Midnight'],
    inStock: true
  },
  {
    id: '14',
    name: 'Minimalist Wall Clock',
    price: 120,
    originalPrice: 150,
    image: '/product-14-wall-clock.webp',
    images: ['/product-14-wall-clock.webp', '/lifestyle-decor.webp'],
    rating: 4.8,
    reviews: 35,
    category: 'Home Decor',
    discount: 20,
    description: 'Sleek, silent wall clock with a brushed metal frame and no-number design.',
    colors: ['Silver', 'Black'],
    inStock: true
  },
  {
    id: '15',
    name: 'Leather Weekend Bag',
    price: 320,
    image: '/product-15-leather-weekend-bag.webp',
    images: ['/product-15-leather-weekend-bag.webp', '/ducati-bag.webp'],
    rating: 5.0,
    reviews: 8,
    category: 'Accessories',
    isFeatured: true,
    description: 'Premium full-grain leather bag, perfect for short trips and cabin luggage.',
    colors: ['Cognac', 'Espresso'],
    inStock: true
  },
  {
    id: '16',
    name: 'Ceramic Candle Holder',
    price: 45,
    image: '/product-16-ceramic-candle-holder.webp',
    images: ['/product-16-ceramic-candle-holder.webp', '/lifestyle-decor.webp'],
    rating: 4.7,
    reviews: 22,
    category: 'Home Decor',
    isNew: true,
    description: 'Handcrafted ceramic candle holder with a unique reactive glaze finish.',
    colors: ['Stone', 'Moss'],
    inStock: true
  },
  {
    id: '17',
    name: 'Denim Overshirt',
    price: 95,
    originalPrice: 130,
    image: '/product-17-denim-overshirt.webp',
    images: ['/product-17-denim-overshirt.webp', '/lifestyle-tee.webp'],
    rating: 4.6,
    reviews: 19,
    category: 'Clothing',
    discount: 27,
    description: 'Heavyweight denim overshirt with reinforced stitching and utility pockets.',
    colors: ['Indigo', 'Washed Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true
  },
  {
    id: '18',
    name: 'Wool Blend Beanie',
    price: 35,
    image: '/product-18-wool-beanie.webp',
    images: ['/product-18-wool-beanie.webp', '/lifestyle-cap.webp'],
    rating: 4.8,
    reviews: 45,
    category: 'Accessories',
    description: 'Soft wool blend beanie with a classic ribbed knit and fold-over cuff.',
    colors: ['Charcoal', 'Oatmeal', 'Rust'],
    inStock: true
  },
  {
    id: '19',
    name: 'Abstract Art Print',
    price: 75,
    image: '/product-19-abstract-art-print.webp',
    images: ['/product-19-abstract-art-print.webp', '/lifestyle-decor.webp'],
    rating: 4.9,
    reviews: 14,
    category: 'Home Decor',
    isFeatured: true,
    description: 'Limited edition abstract art print on archival quality textured paper.',
    colors: ['Multicolor'],
    sizes: ['18x24', '24x36'],
    inStock: true
  },
  {
    id: '20',
    name: 'Linen Button-Down',
    price: 78,
    originalPrice: 110,
    image: '/product-20-linen-button-down.webp',
    images: ['/product-20-linen-button-down.webp', '/lifestyle-tee.webp'],
    rating: 4.7,
    reviews: 31,
    category: 'Clothing',
    discount: 29,
    isNew: true,
    description: 'Breathable 100% linen shirt with a relaxed fit and mother-of-pearl buttons.',
    colors: ['White', 'Sky Blue', 'Sand'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true
  },
  {
    id: '21',
    name: 'Sunglasses - Classic Aviator',
    price: 155,
    image: '/product-21-aviator-sunglasses.webp',
    images: ['/product-21-aviator-sunglasses.webp', '/lifestyle-cap.webp'],
    rating: 4.8,
    reviews: 26,
    category: 'Accessories',
    description: 'Timeless aviator sunglasses with polarized lenses and gold-tone frames.',
    colors: ['Gold/Green', 'Black/Gray'],
    inStock: true
  },
  {
    id: '22',
    name: 'Velvet Accent Pillow',
    price: 38,
    image: '/product-22-velvet-pillow.webp',
    images: ['/product-22-velvet-pillow.webp', '/lifestyle-decor.webp'],
    rating: 4.6,
    reviews: 42,
    category: 'Home Decor',
    description: 'Ultra-soft velvet pillow with a feather down insert and hidden zipper.',
    colors: ['Emerald', 'Ruby', 'Navy'],
    inStock: true
  },
  {
    id: '23',
    name: 'Denim Jacket - Vintage Wash',
    price: 110,
    originalPrice: 160,
    image: '/product-23-denim-jacket.webp',
    images: ['/product-23-denim-jacket.webp', '/lifestyle-tee.webp'],
    rating: 4.7,
    reviews: 18,
    category: 'Clothing',
    discount: 31,
    description: 'Classic denim jacket with a vintage wash and copper buttons.',
    colors: ['Vintage Blue'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true
  },
  {
    id: '24',
    name: 'Ceramic Serving Bowl',
    price: 65,
    image: '/product-24-ceramic-bowl.webp',
    images: ['/product-24-ceramic-bowl.webp', '/lifestyle-decor.webp'],
    rating: 4.9,
    reviews: 12,
    category: 'Home Decor',
    isNew: true,
    description: 'Large ceramic serving bowl with a hand-painted rim.',
    colors: ['Cream'],
    inStock: true
  },
  {
    id: '25',
    name: 'Leather Belt - Classic Brown',
    price: 45,
    image: '/product-25-leather-belt.webp',
    images: ['/product-25-leather-belt.webp', '/lifestyle-tote.webp'],
    rating: 4.8,
    reviews: 54,
    category: 'Accessories',
    description: 'Durable leather belt with a solid brass buckle.',
    colors: ['Tan', 'Dark Brown'],
    inStock: true
  },
  {
    id: '26',
    name: 'Cotton Oxford Shirt',
    price: 68,
    originalPrice: 90,
    image: '/product-26-oxford-shirt.webp',
    images: ['/product-26-oxford-shirt.webp', '/lifestyle-tee.webp'],
    rating: 4.6,
    reviews: 29,
    category: 'Clothing',
    discount: 24,
    description: 'Essential cotton oxford shirt with a button-down collar.',
    colors: ['White', 'Light Blue', 'Pink'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true
  },
  {
    id: '27',
    name: 'Woven Floor Rug',
    price: 240,
    image: '/product-27-woven-rug.webp',
    images: ['/product-27-woven-rug.webp', '/lifestyle-decor.webp'],
    rating: 4.7,
    reviews: 15,
    category: 'Home Decor',
    isFeatured: true,
    description: 'Hand-woven wool rug with a subtle geometric pattern.',
    colors: ['Sand/Gray'],
    sizes: ['5x8', '8x10'],
    inStock: true
  },
  {
    id: '28',
    name: 'Knit Polo Shirt',
    price: 58,
    image: '/product-28-knit-polo.webp',
    images: ['/product-28-knit-polo.webp', '/lifestyle-tee.webp'],
    rating: 4.5,
    reviews: 21,
    category: 'Clothing',
    isNew: true,
    description: 'Soft knit polo shirt with a three-button placket.',
    colors: ['Navy', 'Charcoal'],
    sizes: ['M', 'L', 'XL'],
    inStock: true
  },
  {
    id: '29',
    name: 'Stainless Steel Water Bottle',
    price: 32,
    image: '/product-29-water-bottle.webp',
    images: ['/product-29-water-bottle.webp', '/lifestyle-tote.webp'],
    rating: 4.9,
    reviews: 88,
    category: 'Accessories',
    description: 'Vacuum-insulated water bottle that keeps drinks cold for 24 hours.',
    colors: ['Silver', 'Matte Black'],
    inStock: true
  },
  {
    id: '30',
    name: 'Scented Soy Candle',
    price: 28,
    image: '/product-30-soy-candle.webp',
    images: ['/product-30-soy-candle.webp', '/lifestyle-decor.webp'],
    rating: 4.8,
    reviews: 42,
    category: 'Home Decor',
    description: 'Hand-poured soy candle with notes of sandalwood and cedar.',
    colors: ['Amber Glass'],
    inStock: true
  },
  {
    id: '31',
    name: 'Graphic Fleece Sweatshirt',
    price: 75,
    originalPrice: 100,
    image: '/product-31-fleece-sweatshirt.webp',
    images: ['/product-31-fleece-sweatshirt.webp', '/ducati-sweatshirt.webp'],
    rating: 4.7,
    reviews: 24,
    category: 'Clothing',
    discount: 25,
    isFeatured: true,
    description: 'Cozy fleece sweatshirt with a bold minimalist graphic.',
    colors: ['Off-White', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true
  },
  {
    id: '32',
    name: 'Linen Napkin Set',
    price: 42,
    image: '/product-32-linen-napkins.webp',
    images: ['/product-32-linen-napkins.webp', '/lifestyle-decor.webp'],
    rating: 4.9,
    reviews: 11,
    category: 'Home Decor',
    isNew: true,
    description: 'Set of four pre-washed linen napkins in a muted earth tone.',
    colors: ['Terracotta', 'Sage'],
    inStock: true
  },
  {
    id: '33',
    name: 'Coca-Cola Classic Hoodie',
    price: 72,
    originalPrice: 95,
    image: '/coca-cola-hoodie.webp',
    images: ['/coca-cola-hoodie.webp', '/lifestyle-hoodie.webp'],
    rating: 4.7,
    reviews: 33,
    category: 'Clothing',
    discount: 24,
    isNew: true,
    description: 'Vintage-inspired hoodie with retro cola aesthetic. Soft fleece interior for everyday comfort.',
    colors: ['Red', 'Cream'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true
  },
  {
    id: '34',
    name: 'Guinness Heritage Cap',
    price: 32,
    originalPrice: 42,
    image: '/guinness-cap.webp',
    images: ['/guinness-cap.webp', '/guinness-mug.webp'],
    rating: 4.8,
    reviews: 27,
    category: 'Accessories',
    discount: 24,
    isNew: true,
    description: 'Classic distressed cap with heritage embroidery. Adjustable strap and soft cotton twill construction.',
    colors: ['Black', 'Navy'],
    inStock: true
  },
  {
    id: '35',
    name: 'Budweiser Logo Hoodie',
    price: 68,
    originalPrice: 88,
    image: '/budweiser-hoodie.webp',
    images: ['/budweiser-hoodie.webp', '/budweiser-tee.webp'],
    rating: 4.6,
    reviews: 41,
    category: 'Clothing',
    discount: 23,
    isFeatured: true,
    description: 'Retro-inspired pullover hoodie with vintage beer graphic styling. Brushed fleece interior.',
    colors: ['Heather Gray', 'Burgundy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true
  },
  {
    id: '36',
    name: 'Ducati Milano Crossbody',
    price: 185,
    image: '/ducati-bag.webp',
    images: ['/ducati-bag.webp', '/lifestyle-tote.webp'],
    rating: 4.9,
    reviews: 16,
    category: 'Accessories',
    isFeatured: true,
    description: 'Compact crossbody bag with racing-inspired detailing. Perfect for daily essentials on the go.',
    colors: ['Black', 'Racing Red'],
    inStock: true
  },
  {
    id: '37',
    name: 'Ducati Racing Crewneck',
    price: 79,
    originalPrice: 99,
    image: '/ducati-sweatshirt.webp',
    images: ['/ducati-sweatshirt.webp', '/lifestyle-hoodie.webp'],
    rating: 4.7,
    reviews: 38,
    category: 'Clothing',
    discount: 20,
    isNew: true,
    description: 'Motorsport-inspired crewneck sweatshirt with bold chest graphic. Mid-weight cotton blend.',
    colors: ['Black', 'White'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true
  },
  {
    id: '38',
    name: 'Grey Goose Statement Jacket',
    price: 198,
    originalPrice: 260,
    image: '/grey-goose-jacket.webp',
    images: ['/grey-goose-jacket.webp', '/lifestyle-tee.webp'],
    rating: 4.8,
    reviews: 22,
    category: 'Clothing',
    discount: 24,
    description: 'Premium lightweight jacket with clean lines and subtle branding. Water-resistant finish.',
    colors: ['Charcoal', 'Stone'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true
  },
  {
    id: '39',
    name: 'Grey Goose Court Sneakers',
    price: 135,
    originalPrice: 165,
    image: '/grey-goose-sneakers.webp',
    images: ['/grey-goose-sneakers.webp', '/lifestyle-sneakers.webp'],
    rating: 4.9,
    reviews: 47,
    category: 'Clothing',
    discount: 18,
    isFeatured: true,
    description: 'Low-profile leather sneakers with minimalist silhouette. Cushioned insole for all-day wear.',
    colors: ['White', 'Gray'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    inStock: true
  },
  {
    id: '40',
    name: 'Chevrolet Heritage Tote',
    price: 48,
    image: '/chevrolet-tote.webp',
    images: ['/chevrolet-tote.webp', '/chevrolet-cap.webp'],
    rating: 4.7,
    reviews: 29,
    category: 'Accessories',
    description: 'Roomy canvas tote with vintage automotive embroidery. Reinforced handles and interior pocket.',
    colors: ['Natural', 'Black'],
    inStock: true
  },
]

export function getProductById(id: string): Product | undefined {
  return mockProducts.find(p => p.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  return mockProducts.filter(p => p.category === category)
}

export function getRelatedProducts(productId: string, limit = 4): Product[] {
  const product = getProductById(productId)
  if (!product) return []
  
  return mockProducts
    .filter(p => p.category === product.category && p.id !== productId)
    .slice(0, limit)
}
